# -*- coding: utf-8 -*-
"""Instalacion_De_Opencv_Onnx.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVQWL8wGWNOaJUWk9wqT49fNyuKw_7wu

# **Instalando OpenCv y Onnx Runtime**

# **OPENCV**
"""

sudo apt-get update
sudo apt-get upgrade

"""Instalar las dependencias necesarias:"""

sudo apt-get install build-essential cmake git pkg-config libgtk-3-dev libavcodec-dev libavformat-dev libswscale-dev libv4l-dev libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev gfortran openexr libatlas-base-dev python3-dev python3-numpy libtbb2 libtbb-dev libdc1394-22-dev

"""Clonar el repositorio de OpenCV

Compilar e instalar
"""

cd ~/opencv_build/opencv
mkdir build && cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=~/opencv_build/opencv_contrib/modules -D BUILD_EXAMPLES=ON ..

make -j8

"""Instala OpenCV"""

sudo make install
sudo ldconfig

"""# **Uso de OpenCV con C++**

Guarda tu código fuente en un archivo, por ejemplo, main.cpp.        
Usa el siguiente comando para compilar tu programa:
"""

g++ main.cpp -o output `pkg-config --cflags --libs opencv4`

"""Ejecuta tu programa"""

./output

"""# **ONNX RUNTIME**"""

sudo apt-get update
sudo apt-get upgrade

"""Instalar dependencias necesarias"""

sudo apt-get install -y build-essential cmake curl

"""Instalación de ONNX Runtime"""

pip install onnxruntime

python -c "import onnxruntime as ort; print(ort.__version__)"

"""Clonar el repositorio de ONNX Runtime"""

git clone --recursive https://github.com/microsoft/onnxruntime
cd onnxruntime

"""Configurar y compilar ONNX Runtime"""

./build.sh --config Release --build_shared_lib --parallel --build_wheel

"""Instalar ONNX Runtime"""

pip install ./build/Linux/Release/dist/onnxruntime*.whl

"""## **Usar ONNX Runtime con C++**

Compilar tu proyecto
"""

g++ -I /path_to_onnxruntime/include -L /path_to_onnxruntime/lib -o main main.cpp -lonnxruntime

"""Ejecutar tu programa"""

./main

"""Teseract tambien

"""

sudo apt-get install tesseract-ocr